import type { IncomingHttpHeaders, IncomingMessage } from "node:http";

/**
 * The agent-shim-internal headers the launcher injects through `ANTHROPIC_CUSTOM_HEADERS` so the front door can identify and route a request's session. None of them may ever leave the machine: the identity step strips every one before a route sees the request, so no upstream, and not even the headroom hop, learns what they say.
 */
export const INTERNAL_HEADER_NAMES = [
  "x-agent-shim-identity",
  "x-agent-shim-session",
  "x-agent-shim-headroom",
  "x-agent-shim-auth",
  "x-agent-shim-provider",
  "x-agent-shim-hop",
  "x-agent-shim-hop-id",
  "x-headroom-project-id",
  "x-headroom-session-id",
  "x-headroom-base-url",
] as const;

/** Carries the launching identity's name (the `@name` the launch resolved), set by the launcher and stripped at the door. */
export const IDENTITY_HEADER = "x-agent-shim-identity";

/** Carries one launch's session id, generated by the launcher and stripped at the door; response middleware keys its observations by it. */
export const SESSION_HEADER = "x-agent-shim-session";

/** Names the provider a launch selected, set by the launcher and stripped at the door: the door, not the child, decides where that session's inference goes (see `createProviderRouteResolver`). The headroom hop re-sets it on its own request, exactly as it does the project identity, so the direct listener can resolve the provider after the path-based forms of identification have been reduced to a bare API path. */
export const PROVIDER_HEADER = "x-agent-shim-provider";

/** Set to `1` when the launch resolved headroom on, so the front door knows this session's requests must take the headroom hop; stripped at the door. */
export const HEADROOM_FLAG_HEADER = "x-agent-shim-headroom";

/**
 * Carries the project identity headroom scopes its memory state to (the git repository root of the launch directory). Also injected by the launcher and stripped at the door: the headroom hop re-sets it on its own request, so it reaches headroom and nowhere else.
 */
export const PROJECT_ID_HEADER = "x-headroom-project-id";

/**
 * Headroom's per-session attribution id, the key its `/stats/sessions/<id>` serves: the daemon attributes a request only when it carries this header (or the client's own `x-claude-code-session-id`, which no routed client sends). Re-set by the headroom hop from the launch's own session id, so the daemon attributes traffic the client itself never identifies; inbound copies are stripped at the identity step like every other internal header.
 */
export const SESSION_ATTRIBUTION_HEADER = "x-headroom-session-id";

/**
 * Headroom's per-request upstream selector, which the child used to carry and the door now owns: the door strips any inbound copy (a leftover from an older launcher's environment would otherwise redirect the daemon behind the door's back) and its hop sets it fresh when a route names an upstream.
 */
export const HEADROOM_BASE_URL_HEADER = "x-headroom-base-url";

/**
 * The per-launch capability a client-facing listener requires before it routes anything: a random token the launcher generates, hands the child through `ANTHROPIC_CUSTOM_HEADERS`, and records in the door's session registry, so a loopback process that never launched through agent-shim cannot spend the session's credentials or quota. Stripped at the door like every internal header.
 */
export const AUTH_HEADER = "x-agent-shim-auth";

/**
 * The capability the direct listener requires: a per-generation random secret held only in the door process's memory, set by the headroom hop on the requests it forwards back. A loopback process that finds the direct port still cannot use it, and nothing on disk ever holds the secret.
 */
export const HOP_SECRET_HEADER = "x-agent-shim-hop";

/**
 * Names the credential custody record one headroom hop holds: a random id the hop sets on the request it hands headroom, alongside placeholders where the real credential headers were. The direct listener exchanges a live id (and only for the provider the record was made for) for the real headers before routing, so the credential itself never crosses headroom or the plain-HTTP leg back.
 */
export const HOP_ID_HEADER = "x-agent-shim-hop-id";

/** What the identity step learned about one request from the launcher-injected headers. */
export interface SessionIdentity {
  /** The identity name the launch resolved, when it resolved one. */
  readonly identity: string | undefined;
  /** The per-launch session id, when the launcher injected one. */
  readonly sessionId: string | undefined;
  /** The provider this launch selected, when it selected one: the door routes the session's API traffic to that provider whatever host the child believes it is dialling. */
  readonly provider: string | undefined;
  /** Whether this launch resolved headroom on, so its requests must pass through the headroom hop before their route. */
  readonly headroom: boolean;
  /** The project identity headroom scopes memory to, re-set on the headroom hop and sent nowhere else. */
  readonly projectId: string | undefined;
}

/** The outcome of the pipeline's first step: what the session is, and the headers that may actually leave the machine. */
export interface IdentifiedRequest {
  readonly session: SessionIdentity;
  /**
   * The request's headers with every internal header removed. A route forwards these, and only these, onwards: the identity and session headers are for the front door alone and must never reach an upstream, the headroom hop, or a translator's backend call.
   */
  readonly forwardableHeaders: IncomingHttpHeaders;
}

/** Reads one header's single value, joining a repeated header the way a recipient that cares would: last write wins is wrong for an injected identity, so repeats are joined with `, ` rather than silently dropped. */
function singleHeaderValue(value: string | readonly string[] | undefined): string | undefined {
  if (typeof value === "string") {
    return value;
  }
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  return undefined;
}

/** Reads one internal header's value whatever case its name arrived in: Node lowercases the names it hands the pipeline, but a test or future transport need not. */
export function internalHeaderValue(headers: Readonly<IncomingHttpHeaders>, name: string): string | undefined {
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === name) {
      return singleHeaderValue(value);
    }
  }
  return undefined;
}

/**
 * The identity step: splits a request's headers into what the front door may learn (the session) and what may leave the machine (everything else). Internal header names are matched case-insensitively, which is how the transport already normalises them.
 */
export function identifyRequest(headers: Readonly<IncomingHttpHeaders>): IdentifiedRequest {
  const internal = new Set<string>(INTERNAL_HEADER_NAMES);
  const forwardable: Record<string, string | string[] | undefined> = {};
  for (const [name, value] of Object.entries(headers)) {
    if (value !== undefined && !internal.has(name.toLowerCase())) {
      forwardable[name] = value;
    }
  }
  return {
    session: {
      identity: internalHeaderValue(headers, IDENTITY_HEADER),
      sessionId: internalHeaderValue(headers, SESSION_HEADER),
      provider: internalHeaderValue(headers, PROVIDER_HEADER),
      headroom: internalHeaderValue(headers, HEADROOM_FLAG_HEADER) === "1",
      projectId: internalHeaderValue(headers, PROJECT_ID_HEADER),
    },
    forwardableHeaders: forwardable,
  };
}

/** The path prefix every provider-scoped request sits under: the door rewrites a provider session's bare API paths under it (see `createProviderRouteResolver`), and a child still pointed at a provider-scoped base URL by an earlier launch is answered from it, so one listener serves any number of providers, each with its own credential and translation settings. */
export const PROVIDER_PATH_PREFIX = "/providers/";

/** The bare origin of a loopback listener, which is what a headroom hop is told to forward to: headroom appends the client's own request path to it. */
export function directOrigin(port: number): string {
  return `http://127.0.0.1:${String(port)}`;
}

/** Splits `/providers/<name>/<rest>` into the provider name and the rest, or undefined for any other path. */
export function parseProviderPath(path: string): { readonly provider: string; readonly rest: string } | undefined {
  if (!path.startsWith(PROVIDER_PATH_PREFIX)) {
    return undefined;
  }
  const tail = path.slice(PROVIDER_PATH_PREFIX.length);
  const slash = tail.indexOf("/");
  if (slash <= 0) {
    return undefined;
  }
  return { provider: decodeURIComponent(tail.slice(0, slash)), rest: tail.slice(slash) };
}

/** One request as a route sees it: the transport's own request and abort signal, plus what the identity step resolved. */
export interface RoutedRequest {
  readonly method: string;
  /** The request target exactly as received, path and query together. */
  readonly url: string;
  /** The request's headers with every internal header already stripped: exactly what a route may forward onwards. */
  readonly headers: IncomingHttpHeaders;
  /** The request's body stream: a route either pipes it onward untouched or reads it whole, never both. */
  readonly body: IncomingMessage;
  /** Aborted the moment the client goes away; a route aborts its own upstream work with it. */
  readonly signal: AbortSignal;
  readonly session: SessionIdentity;
}

/** The response half a route writes through, so the pipeline can run response middleware at the head and apply backpressure uniformly. */
export interface RoutedResponse {
  /** Whether the head has already been written. */
  readonly headersSent: boolean;
  /** Writes the response head, running every response observer first. Must be called exactly once, before any write. */
  readonly start: (status: number, headers: Readonly<Record<string, string>>) => void;
  /** Sends the head on its way before any body chunk exists: a streaming response's client should see its headers the moment they are known. */
  readonly flush: () => void;
  /**
   * Writes one body chunk, waiting for the socket to take it when the client is slow (backpressure: a slow client slows the route, and its upstream, instead of growing a buffer without bound). Resolves early, without writing, once the client is gone.
   */
  readonly write: (chunk: string | Uint8Array) => Promise<void>;
  /** Ends the response. */
  readonly end: () => void;
  /** Drops the connection: an upstream failure after the head went out, where no status can be sent any more. */
  readonly destroy: () => void;
}

/** One pluggable destination the front door routes a request to. */
export interface FrontDoorRoute {
  /** The route's name, for logs and for response middleware context. */
  readonly name: string;
  /**
   * Whether the headroom hop may sit in front of this route. Headroom needs the Anthropic-shaped request, so a protocol translator built on an Anthropic-compatible surface opts in, and a route whose request shape headroom could not understand opts out.
   */
  readonly headroomEligible: boolean;
  /**
   * The upstream headroom is told to use (its per-request base URL header) when the hop sits in front of this route. When defined it is always this door's direct listener, which is what lets the hop keep the route's credential in custody and the direct listener restore it; a route must never name any other address here. Undefined leaves headroom's own default upstream in charge, which is Claude Code's API.
   */
  readonly headroomUpstream: string | undefined;
  /**
   * Serves the request directly: headroom has already been applied, or does not apply to this route. Writes the response through `response` and resolves once the response has ended.
   */
  readonly serve: (request: RoutedRequest, response: RoutedResponse) => Promise<void>;
}
